/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TimeAgo from 'javascript-time-ago'
import ar from 'javascript-time-ago/locale/ar'
import Link from 'next/link'

TimeAgo.addDefaultLocale(ar)

const ChatHistory: React.FC<{conversations : any}> = ({conversations}) => {

const timeAgo = new TimeAgo('ar')

  return (
    <div>
        <div className=" text-neutral-700 z-20">
            <span className="flex h-9 items-center"><h3 className="pb-2 pt-3 px-2 text-xs font-semibold text-ellipsis overflow-hidden break-all text-token-text-primary">سجل المحادثات</h3></span></div>
            {conversations.map((conversation, index) => (
                <div key={`conversation-${index}`}>
                <Link href={`/chat/${conversation.conversation_id}`} className="block max-w-sm m-1 rounded-lg mt-2  hover:bg-neutral-200 hover:bg-opacity-50">
                    <p className="font-normal text-sm text-neutral-700 gap-2 p-2">{conversation.messages[0].content}</p>
                    <p className="font-normal text-xs text-neutral-500 px-2">{timeAgo.format(new Date(conversation.messages[0].date * 1000) )}</p>
                </Link>
                </div> 
                ))}
    </div>
  );
};

export default ChatHistory;
