/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex overflow-hidden gap-10 justify-between items-center px-6 py-1.5 w-full text-sm font-medium tracking-normal leading-none whitespace-nowrap bg-white min-h-[32px] text-zinc-800">
      <time className="self-stretch my-auto">9:30</time>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d4b3d161820e6fad1e5f735935c6899aa8b1060c58790cb419f27e8cb1fed26?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto aspect-[2.7] w-[46px]"
      />
    </header>
  );
};

export default Header;
