"use client"

/**
 * This code was generated by Builder.io.
 */
import React, { useState, useEffect, useRef } from 'react';
import Header from "./Header";
import ProfileSection from "./ProfileSection";
import SuggestedQuestions from "./SuggestedQuestions";
import InputSection from "./InputSection";
import ChatMessage from '@/components/chat/ChatMessage';
import useLocalStorage from './sessionId';
import ChatHistory from './ChatHistory';
import { v4 as uuidv4 } from 'uuid';
import { API_URL } from "@/config";

const MouminAI: React.FC = () => {

  const bottomRef = useRef(null);
  const [responseData, setResponseData] = useState(null);
  const [messages, setMessages] = useState([])
  const [sessionId, setSessionId] = useLocalStorage('sessionId', uuidv4())
  const [conversations, setConversations] = useState([])
  const  [conversation_id] = useState(uuidv4());

  let uniqe_id = uuidv4()

  const scrollToBottom = () => {
    const container = bottomRef.current;
    container.scrollTop = container.scrollHeight;
  };

  useEffect(() => {

    if (sessionId == null) {
      setSessionId(uuidv4())
      return
    }

    const getData = async () => {

      try {
             
        const response = await fetch(`${API_URL}/conversations`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ 
            "sessionId": sessionId ?? uniqe_id,
           }),
        });
  
  
        if (!response.ok) {
          throw new Error('Something went wrong');
        }
  
        const data = await response.json();
        
        setConversations(JSON.parse(data))

        // Handle response data here
      } catch (error) {
       
        console.error('Error:', error);
        // Handle error here
      }

      
    }

    getData()
    
  }, [sessionId])

  const addFeedback = async (itemIndex : Number, score : Number) => {

    let item = messages[itemIndex]

    try {
     
      const response = await fetch(`${API_URL}/feedback`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          "feedback_value": score,
          "trace_id": item.trace_id
         }),
      });


      if (!response.ok) {
        throw new Error('Something went wrong');
      }

      const data = await response.json();

      const updatedMessages = messages.map((message, idx) => {
        if (idx === itemIndex) {
          return { ...message, feedback: score }; // Increase the likes for the clicked message
        }
        return message; // Return the rest of the messages unchanged
      });
  
      // Update the state with the new array
      setMessages(updatedMessages);

      console.log(data)
      // Handle response data here
    } catch (error) {
     
      console.error('Error:', error);
      // Handle error here
    }

  }

  const handleFormSubmit = (data : any) => {
    setResponseData(data);
  };

  useEffect(() => {
    if (responseData) {
      if (responseData.status == "user"){
        setMessages([...messages, responseData, {status: 'sending'}])
        setTimeout(() => {
          scrollToBottom()
        }, 100)
      }else if (responseData.status == "assistant"){
        setMessages((prevMessages) => {
          const updatedMessages = [...prevMessages];
          updatedMessages[updatedMessages.length - 1] = responseData
          return updatedMessages;
        });
        setTimeout(() => {
          scrollToBottom()
        }, 100)
      }
    }
  }, [responseData]); 

  return (
    <div className='relative flex h-full w-full bg-neutral-100 overflow-hidden transition-colors z-0'>
      
      <div className="z-[1] bg-neutral-100 flex-shrink-0 overflow-x-hidden bg-neutral-100 border-l max-md:!w-0 hidden md:block fixed top-0 right-0 h-full pt-[56px]" style={{ "width": "260px" }}>
        <ChatHistory conversations={conversations} />
      </div>

      <div className='relative flex h-full max-w-full flex-1 flex-col overflow-hidden'>
        
        <div className='draggable sticky top-0 z-10 flex min-h-[56px] items-center justify-center border-transparent bg-token-main-surface-primary pl-0 '>
          <ProfileSection />
        </div> 
     
    <main className='relative h-full w-full flex-1 overflow-auto transition-width'>
    <div className='composer-parent flex h-full flex-col focus-visible:outline-0'>
      <div className='relative flex max-w-full flex-1 flex-col overflow-hidden'>

          {messages.length == 0 ? (
            <>
              <SuggestedQuestions />
            </>
          ) : (

                  <div ref={bottomRef} className="flex-1 overflow-x-hidden scroll-smooth font-medium self-center text-neutral-900 text-opacity-90">
                    <div className='h-full'>
                      {messages.map((message, index) => (
                        <div  key={index}  className='w-full text-token-text-primary focus-visible:outline-2 focus-visible:outline-offset-[-4px]'>
                          <div className='m-auto text-lg py-[18px] px-3 md:px-4 w-full md:px-5 lg:px-4 xl:px-5'>
                            <ChatMessage
                              sender={message.status}
                              content={message.content}
                              index={index}
                              item={message}
                              addFeedback={addFeedback}
                            />
                          </div>
                        </div>
                      ))}
                      </div>
              </div>

)}
          
          </div>

        <div className='md:pt-0 dark:border-white/20 md:border-transparent md:dark:border-transparent w-full'>
          <InputSection sessionId={sessionId} onFormSubmit={handleFormSubmit} conversation_id={conversation_id} />
          <div className='text-center text-black text-opacity-50 text-sm my-2'>النموذج مازال في مرحلة الإختبار والتطوير, بعض الإجابات قد تكون غير دقيقة</div>
        </div>

        </div>
    
    </main>

    </div>

    </div>
  );

};

export default MouminAI;
