/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProfileSection: React.FC = () => {
  return (
    <section className="flex overflow-hidden gap-4 items-center pr-4 pl-1 w-full bg-white border-b border-gray-200 min-h-[56px]">
      <div className="flex items-center self-stretch my-auto w-12">
        <div className="flex gap-2 justify-center items-center self-stretch my-auto w-12 min-h-[48px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9998356751ee9238d89239a58a0d1b43b735d317a653192f78beaf8e9cd2321?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
            alt=""
            className="object-contain self-stretch my-auto w-6 aspect-square"
          />
        </div>
      </div>
      <h1 className="flex-1 shrink self-stretch my-auto text-xl font-medium text-right basis-0 text-ellipsis text-zinc-800">
        المساعد الذكي مؤمن
      </h1>
    </section>
  );
};

export default ProfileSection;
