/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavItemProps {
  icon: string;
  label: string;
  isActive?: boolean;
}

const NavItem: React.FC<NavItemProps> = ({ icon, label, isActive = false }) => {
  const textColorClass = isActive ? "text-emerald-700" : "text-neutral-400";
  const fontWeightClass = isActive ? "font-bold" : "font-medium";

  return (
    <div
      className={`flex overflow-hidden flex-col flex-1 shrink items-center py-2 text-xs ${fontWeightClass} whitespace-nowrap basis-0 min-h-[56px] min-w-[55px] ${textColorClass}`}
    >
      <img
        loading="lazy"
        src={icon}
        className="object-contain w-6 rounded-md aspect-square"
        alt=""
      />
      <div className="mt-1">{label}</div>
    </div>
  );
};

interface BottomNavigationProps {}

const BottomNavigation: React.FC<BottomNavigationProps> = () => {
  return (
    <nav className="flex overflow-hidden gap-2 items-start px-2 mt-2 w-full border-t border-gray-200 bg-neutral-100">
      <NavItem
        icon="https://cdn.builder.io/api/v1/image/assets/TEMP/882d40d567c084bfef8e837cfdad949e1634f44ee8692e38063d4dae12296bdb?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
        label="الإعدادات"
      />
      <NavItem
        icon="https://cdn.builder.io/api/v1/image/assets/TEMP/83aaf8943a1590bdbfc59a059a8f264bd10a6e88b562ef92154ea634a6585adb?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
        label="المفضلة"
      />
      <NavItem
        icon="https://cdn.builder.io/api/v1/image/assets/TEMP/f5c10831626597ec2728e4907ef2e8138f90b1ec9032892a9c084b016cfb09a4?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
        label="مؤمن AI"
        isActive={true}
      />
      <NavItem
        icon="https://cdn.builder.io/api/v1/image/assets/TEMP/f90fd6368d31670f2e253db4ecf877944979c485003f19df2618c652a76245c4?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
        label="الأقسام"
      />
      <div className="flex overflow-hidden flex-col flex-1 shrink items-center py-2 basis-0 min-h-[56px] min-w-[55px]">
        <div className="flex overflow-hidden flex-col w-6 rounded-[100px]">
          <div className="flex shrink-0 w-full h-6 bg-blend-lighten bg-neutral-400" />
        </div>
        <div className="mt-1 text-xs font-medium text-neutral-400">
          الرئيسية
        </div>
      </div>
      <div className="flex flex-col flex-1 shrink justify-center items-center py-2 basis-0 bg-neutral-100 min-h-[16px] min-w-[288px]">
        <div className="flex max-w-full rounded-lg bg-neutral-500 min-h-[3px] w-[120px]" />
      </div>
    </nav>
  );
};

export default BottomNavigation;
