/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  return (
    <header>
      <div className="flex overflow-hidden gap-10 justify-between items-center px-6 py-1.5 w-full text-sm font-medium tracking-normal leading-none whitespace-nowrap bg-white min-h-[32px] text-zinc-800">
        <div className="self-stretch my-auto">9:30</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d4b3d161820e6fad1e5f735935c6899aa8b1060c58790cb419f27e8cb1fed26?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
          className="object-contain shrink-0 self-stretch my-auto aspect-[2.7] w-[46px]"
          alt=""
        />
      </div>
      <div className="flex overflow-hidden gap-4 items-center pr-4 pl-1 w-full bg-white border-b border-gray-200 min-h-[56px]">
        <div className="flex items-center self-stretch my-auto w-12">
          <div className="flex gap-2 justify-center items-center self-stretch my-auto w-12 min-h-[48px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9998356751ee9238d89239a58a0d1b43b735d317a653192f78beaf8e9cd2321?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
              className="object-contain self-stretch my-auto w-6 aspect-square"
              alt=""
            />
          </div>
        </div>
        <div className="flex-1 shrink self-stretch my-auto text-xl font-medium text-right basis-0 text-ellipsis text-zinc-800">
          مؤمن AI
        </div>
      </div>
    </header>
  );
};

export default Header;
