/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InputBarProps {}

const InputBar: React.FC<InputBarProps> = () => {
  return (
    <form className="flex overflow-hidden gap-2 items-center self-center py-1 pr-4 mt-2 w-full bg-white rounded-xl border border-solid border-neutral-900 border-opacity-10 min-h-[56px] shadow-[0px_0px_80px_rgba(0,0,0,0.08)]">
      <label htmlFor="userInput" className="sr-only">
        اكتب سؤالك
      </label>
      <input
        id="userInput"
        type="text"
        className="flex-1 shrink self-stretch my-auto text-sm font-medium text-right basis-0 text-neutral-900 text-opacity-40 bg-transparent border-none outline-none"
        placeholder="اكتب سؤالك"
      />

    <div className="flex gap-2 justify-center items-center self-stretch my-auto w-12 min-h-[48px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/7875f712ebcf40ea4d75685127d45e343865e87ac3cb37c5c9a42d582043c46f?placeholderIfAbsent=true&apiKey=645ca4b112e14229a2cd3203c4a5d6b3"
          className="object-contain self-stretch my-auto w-5 aspect-square"
          alt=""
        />
      </div>

    </form>
  );
};

export default InputBar;
