/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ChatMessage from "./ChatMessage";
import InputBar from "./InputBar";
import BottomNavigation from "./BottomNavigation";

interface MyComponentProps {}

const MyComponent: React.FC<MyComponentProps> = () => {
  const chatMessages = [
    {
      sender: "user",
      message: "السلام عليكم, أنا علي كيف حالك؟",
    },
    {
      sender: "ai",
      message:
        "عليكم السلام علي, أنا مؤمن مساعدك الذكي في رحلتك في إيمانك, ماذا تريد أن تسألني؟",
    },
    {
      sender: "user",
      message: "متى ولد الإمام الحسين عليه السلام؟",
    },
    {
      sender: "ai",
      message:
        "ولد الإمام الحسين بن علي بن أبي طالب عليه السلام في الثالث من شهر شعبان في السنة الرابعة من الهجرة، في المدينة المنورة.",
    },
    {
      sender: "user",
      message: "ما هي واقعة الطف وماذا حدث فيها؟",
    },
    {
      sender: "ai",
      message:
        "واقعة الطف هي واحدة من أهم الأحداث التاريخية في تاريخ الإسلامي. وهي واقعة قتل الإمام الحسين بن علي بن أبي طالب عليه السلام في كربلاء، العراق، في العام 61 للهجرة. \n\nكان الإمام الحسين قد غادر المدينة المنورة متجهاً نحو الكوفة، لكنه اضطر إلى تغيير مسيرة حركته عن الكوفة، وأن يتجه نحو كربلاء بعد أن واجه الحر بن يزيد في منطقة ذو حسم. وقد حل ركب الإمام الحسين في كربلاء في الثاني من محرم سنة 61 للهجرة. وقد حاصرهم جيش الحر من كل مكان، ثم وصل أربعة آلاف مقاتل بقيادة عمر بن سعد إلى كربلاء لمواجهة الإمام الحسين. وقد تمت عدة محادثات بين الإمام الحسين وعمر بن سعد، لكن ابن زياد والي الكوفة خير الإمام الحسين عبر قائد جيشه عمر بن سعد بين البيعة مع يزيد أو الحرب. \n\nوكانت واقعة الطف نتيجة لرفض الإمام الحسين البيعة ليزيد، الذي كان قد نصب نفسه إماماً بعد مقتل خليفته عبد الملك بن مروان. وقد قتل الإمام الحسين في هذه الواقعة، مع أهله وأصحابه، الذين بلغ عددهم 72 شخصاً.",
    },
  ];

  return (
    <main className="flex overflow-hidden flex-col rounded-2xl shadow-sm bg-neutral-100 max-w-[360px]">
      <Header />
      <section className="flex flex-col self-center mt-4 w-full font-medium h-[552px] max-w-[328px] text-neutral-900 text-opacity-90">
        {chatMessages.map((message, index) => (
          <ChatMessage
            key={index}
            sender={message.sender}
            message={message.message}
          />
        ))}
      </section>
      <InputBar />
      <BottomNavigation />
      <style jsx>{`
        builder-component {
          max-width: none !important;
        }
      `}</style>
    </main>
  );
};

export default MyComponent;
